#!/usr/bin/env bash

# Check for required arguments
if [ "$#" -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
KEY_PATH="$4"

# Transfer the file using scp
scp -i "$KEY_PATH" -o StrictHostKeyChecking=no "$FILE_PATH" "${USERNAME}@${SERVER_IP}:~/"
