#!/usr/bin/env bash
# Script to transfer a file to a remote server using SCP

if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE="$1"
IP="$2"
USER="$3"
KEY="$4"

scp -o StrictHostKeyChecking=no -i "$KEY" "$FILE" "${USER}@${IP}:~/"

#Transfers a file to a remote server's home directory using scp

if [ "$#" -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

FILE=$1
IP=$2
USER=$3
KEY=$4

scp -o StrictHostKeyChecking=no -i "$KEY" "$FILE" "$USER@$IP:~/"
Add some_page.html

