#!/usr/bin/env bash
# transfers a file from a client to a server with scp

if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    exit 1
fi

FILE=$1
IP=$2
USER=$3

if [ "$#" -eq 3 ]; then
    scp -o StrictHostKeyChecking=no "$FILE" "$USER@$IP:~/"
else
    KEY=$4
    scp -i "$KEY" -o StrictHostKeyChecking=no "$FILE" "$USER@$IP:~/"
fi
