#!/usr/bin/env bash
# Installs nginx and configures it to return "Hello World!" on root

# Install nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Replace default index page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo service nginx restart

