#!/usr/bin/env bash
# Sets up a 301 redirection on /redirect_me to a YouTube video

# Install nginx if not installed
sudo apt-get update -y
sudo apt-get install nginx -y

# Add the redirection to the default config
sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart
