#!/usr/bin/env bash
# Sets up a custom 404 page for Nginx

# Install nginx if not already installed
sudo apt-get update -y
sudo apt-get install nginx -y

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Edit default nginx config to use the custom 404 page
sudo sed -i "/server_name _;/a \\n\terror_page 404 /custom_404.html;" /etc/nginx/sites-available/default

sudo service nginx restart

