#!/usr/bin/env bash
# Configures a new Ubuntu machine: installs Nginx, sets hostname, adds a custom X-Served-By header

HOSTNAME=$(hostname)
if [[ "$HOSTNAME" != *"web"* ]]; then
  if [ "$(hostname -I | awk '{print $1}')" == "44.201.253.240:80" ]; then
    sudo hostnamectl set-hostname 1302547-web-01  
  else
    sudo hostnamectl set-hostname 1302547-web-02
  fi
fi

# Install nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Set up index.html
echo "Hello World from $(hostname)!" | sudo tee /var/www/html/index.html

# Allow HTTP through UFW
sudo ufw allow 'Nginx HTTP'

# Configure nginx with custom header
HOSTNAME=$(hostname)

sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        add_header X-Served-By $HOSTNAME;
        try_files \$uri \$uri/ =404;
    }

    location = /redirect_me {
        add_header X-Served-By $HOSTNAME;
        return 301 https://www.blog.ehoneahobed.com;
    }
}
EOF

# Restart Nginx
sudo service nginx restart

# X-Served-By: 1302547-web-01
# X-Served-By: 1302547-web-02
