#!/usr/bin/env bash
# Installs and configures HAProxy to load balance traffic to web-01 and web-02

sudo apt-get update -y
sudo apt-get install -y haproxy

# Enable HAProxy
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http-in
    bind *:80
    default_backend web_back

backend web_backend
    balance roundrobin
    server web-01 44.201.253.240:80 check
    server web-02 3.91.102.6:80 check
EOF

# Restart HAProxy
sudo service haproxy restart
