#!/usr/bin/env bash
# Installs and configures HAProxy on the load balancer

# Update and install haproxy
sudo apt-get update
sudo apt-get install -y haproxy

# Enable haproxy via init system
sudo systemctl enable haproxy

# Configure haproxy to balance between web-01 and web-02
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOL

frontend http_front
   bind *:80
   default_backend http_back

backend http_back
   balance roundrobin
   server web-01 44.201.253.240:80 check
   server web-02 3.91.102.6:80 check
EOL

# Restart haproxy
sudo service haproxy restart
